### ISSUE TITLE
[Bug]: Redirecting to wrong panel

### ISSUE THREAD

**Issue by CodeWithDennis** [vormkracht10/filament-two-factor-auth#2]
### What happened?

When adding the 2FA on a panel that isn't the main one, the user will be redirected to the main panel instead of the one where 2FA is set up. For example, if the panel is `/customer/login`, the user will be redirected to `/employees/login`, as that's the main panel.

### How to reproduce the bug

Set up two panels: one for customers and one for employees, and place the login on the employees panel and try logging in (with code).

### Package Version

1.0.0

### PHP Version

8.2

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

### Notes

_(It likely has to do with the response. You might want to retrieve the `Filament::getCurrentPanel()` and then get the route from there.)_

**Comment by Baspa** [comment]
Thank you for your clear explanation of the bug! I'm very sure it has something to do with the response. Tomorrow I have time to take a look at it, I will let you know when I fixed it :) @CodeWithDennis

**Comment by CodeWithDennis** [comment]
> Thank you for your clear explanation of the bug! I'm very sure it has something to do with the response. Tomorrow I have time to take a look at it, I will let you know when I fixed it :) @CodeWithDennis

No problem! Here is some more information. The method `store` on the `TwoFactorAuthenticatedSessionController` class returns the wrong reponse.


```PHP
// Currently
public function store(TwoFactorLoginRequest $request)
{
    ...    
    return app(TwoFactorLoginResponse::class);
}
```

```PHP
// Should be
public function store(TwoFactorLoginRequest $request)
{
    ...
    return app(\Vormkracht10\TwoFactorAuth\Http\Responses\TwoFactorLoginResponse::class);
}
```

The only issue now is that the response is returning the main panel route instead of the panel using 2FA. (Which is the main issue)


```php
return redirect()->intended(Filament::getCurrentPanel()->getUrl());
```

That's as far as I've gotten.

**Comment by Baspa** [comment]
I've made some changes in the [2-bug-redirecting-to-wrong-panel](https://github.com/vormkracht10/filament-two-factor-auth/tree/2-bug-redirecting-to-wrong-panel) branch but in my local repository it still doesn't redirect to the correct panel. Can you verify that it isn't working correctly when checking out that branch? I'm not sure if I have setup the panels correctly. @CodeWithDennis

**Comment by CodeWithDennis** [comment]
If you use Filament::getCurrentPanel() in the response or the class, it will return the main panel. It looks like it can't fetch the original panel because the 2FA page is likely under the default "login" panel. We need to find a way to grab the correct panel or pass it along somehow.

**Comment by Baspa** [comment]
Alright, thanks for checking. I think I've built something like that in a project, will check it later today / tomorrow.

**Comment by Baspa** [comment]
It should be fixed now, can you double check it for me please? Tagged it with tag v1.0.3 @CodeWithDennis

**Comment by CodeWithDennis** [comment]
> It should be fixed now, can you double check it for me please? Tagged it with tag v1.0.3 @CodeWithDennis

Yes! Works perfectly, nice work!
